package com.tech.engg5.batch.processor.enums;

public enum BookBatchFileStatusEnum {
  NO_FILE_FOUND,
  FILE_DOWNLOAD_COMPLETE,
  FILE_DOWNLOAD_FAILED,
  FILE_UNZIP_COMPLETE,
  FILE_UNZIP_FAILED,
  FILE_READ_COMPLETE,
  SAVE_RECORDS_IN_PROGRESS,
  SAVE_RECORDS_COMPLETED,
  SAVE_RECORDS_FAILED,
  FILE_PROCESSING_COMPLETED_ALL_RECORDS,
  FILE_PROCESSING_COMPLETED_FAILED_RECORDS,
  FILE_PROCESS_REINITIATED;
}
